# Generated by Django 5.0 on 2024-01-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerscareer',
            old_name='Years',
            new_name='Seasons',
        ),
    ]
