# Generated by Django 5.0 on 2024-01-02 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0003_proleague_alter_playerscareer_income_nbateam_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images/NBA-Logo-1.jpg'),
            preserve_default=False,
        ),
    ]
