# Generated by Django 5.0 on 2024-01-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0005_remove_nbateam_image_proleague_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='image',
            field=models.ImageField(default='TBA', upload_to='static/images'),
            preserve_default=False,
        ),
    ]
